name: rsd CI

on:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.78.0

permissions:
  contents: read

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            sh.rustup.rs:443
            static.rust-lang.org:443
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=${{ env.RUST_VERSION }} -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup default stable
          rustup component add rustfmt
      - name: Run Checks
        run: |
          cargo fmt --all -- --check
          cargo build --all --release
