name: Build rsd via apko

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            packages.wolfi.dev:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            registry-1.docker.io:443
            storage.googleapis.com:443
            sum.golang.org:443
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: 1.23
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349
      - run: |
          go install chainguard.dev/apko@latest
          go install chainguard.dev/melange@latest
      - run: |
          sudo apt -y update
          sudo apt -y install bubblewrap
          sudo chmod u+s /usr/bin/bwrap
      - run: |
          make rsd-apko
          make rsd-docker
      - run: |
          docker run --rm rsd:latest-amd64
          docker run --rm rsd:latest-arm64
