name: rsd release

on:
  push:
    tags:
      - '*'

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            motd.ubuntu.com:443
            objects.githubusercontent.com:443
            packages.microsoft.com:443
            raw.githubusercontent.com:443
            sh.rustup.rs:443
            static.rust-lang.org:443
            uploads.github.com:443
      - uses: chainguard-dev/actions/setup-gitsign@e82b4e5ae10182af72972addcb3fedf7454621c8
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup default stable
      - name: Build using cargo
        run: |
          cargo build --release
          cp target/release/rsd .
      - name: Generate subject
        id: hash
        run: |
          set -euo pipefail
          echo "hashes=$(sha256sum ./rsd | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: Generate SBOM via Syft
        id: sbom
        uses: anchore/sbom-action@df80a981bc6edbc4e220a492d3cbe9f5547a6e75
        with:
          output-file: ${{ github.workspace }}/rsd-sbom.spdx
      - name: Generate SBOM signature
        id: sbom_signature
        run: |
          set -euo pipefail
          echo "sbom_signature=$(sha256sum ${{ github.workspace }}/rsd-sbom.spdx | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: Upload SBOM signature to release
        run: |
          set -euo pipefail
          echo ${{ steps.sbom_signature.outputs.sbom_signature }} > rsd-sbom.sig
          gh release upload ${{ github.ref_name }} rsd-sbom.sig
        env:
          GH_TOKEN: ${{ github.token }}
  provenance:
    needs:
      - build
    # https://github.com/slsa-framework/slsa-github-generator/issues/722
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: true
